### ISSUE TITLE
How to reproduce your results?

### ISSUE THREAD

**Issue by sherlock1987** [kodenii/CoSDA-ML#4]
Hey, could you guys tell me what the hyperparameters are in this project?
I run your codes but the results are not good as your paper results.
How many epochs does will it get the best result, 10 or 100?

**Comment by kodenii** [comment]
Hi. Because of the difference among the devices, you may need an extra hyper-parameters searching of selection ratio (train.ratio or train.cross). The hyper-parameters we used in our devices are in the configuration file and we did not change them. We have uploaded the checkpoints. Hope these checkpoints can help.
